export const filterButtons = [
  {
    subject: "romance",
  },
  {
    subject: "kids",
  },
  {
    subject: "thrillers",
  },
  {
    subject: "textbooks",
  },
  {
    subject: "fantasy",
  },
  {
    subject: "biographies",
  },
  {
    subject: "recieps",
  },
  {
    subject: "children",
  },
  {
    subject: "medicine",
  },
];

export const responseofGetData = {
  key: "/subjects/children",
  name: "children",
  subject_type: "subject",
  work_count: 53431,
  works: [
    {
      key: "/works/OL138052W",
      title: "Alice's Adventures in Wonderland",
      edition_count: 3557,
      cover_id: 10527843,
      cover_edition_key: "OL31754751M",
      subject: [
        "Alice (fictitious character : carroll), fiction",
        "British and irish fiction (fictional works by one author)",
        "Fiction, fantasy, general",
        "JUVENILE FICTION",
        "classics",
        "Fantasy & Magic",
        "Imagination & Play",
        "adventure and adventurers",
        "adventure and adventurers, fiction",
        "adventure stories",
        "adventure travel",
        "animals",
        "anthropomorphism",
        "artists' illustrated books",
        "books and reading",
        "child and youth fiction",
        "children",
        "children's fiction",
        "children's literature",
        "children's literature, english",
        "children's stories",
        "children's stories, english",
        "classic literature",
        "coloring books",
        "croquet",
        "cuentos infantiles ingleses",
        "curiosidad",
        "curiosidad en los niños",
        "curiosity",
        "curiosity in children",
        "english",
        "english adventure stories",
        "english fantastic fiction",
        "english fantasy fiction",
        "english fantasy literature",
        "english language",
        "english literature",
        "english nonsense verses",
        "fairy tales",
        "fantasy",
        "fantasy fiction",
        "fantasy in fiction",
        "fantasy  magic",
        "fantasía",
        "ficción juvenil",
        "fiction",
        "friendship",
        "girls",
        "girls, fiction",
        "hookahs",
        "humor",
        "humorous stories",
        "illustrations",
        "imaginary places",
        "juvenile literature",
        "legends",
        "literary nonsense",
        "logic",
        "lugares imaginarios",
        "mythical animals",
        "niñas",
        "nonsense verses",
        "novela",
        "novela fantástica",
        "novela juvenil",
        "open library staff picks",
        "picture books",
        "playing cards",
        "rabbits",
        "readers",
        "reading materials",
        "short novel",
        "tea",
        "texts",
        "Alice (Fictitious character : Carroll)",
        "English language, textbooks for foreign speakers",
        "Fantastique",
        "Enfants",
        "Affirmation de soi",
        "Spanish language materials",
        "Alicia (Personaje literario : Carroll)",
        "Spanish language",
        "nyt:chapter-books=2010-02-21",
        "New York Times bestseller",
        "Literatura infanto-juvenil",
        "Literatura inglesa",
        "Carroll, lewis, 1832-1898",
        "Children's literature, history and criticism",
        "Children, books and reading",
        "Crocheting",
        "Fiction, general",
        "Fantasy fiction, history and criticism",
        "Toy and movable books",
        "Imagination",
        "Textbooks for foreign speakers",
        "Readers for new literates",
        "High interest-low vocabulary books",
        "Science fiction",
        "CUENTO INFANTIL INGLES",
        "History and criticism",
        "Translations into Irish",
        "Irish literature",
        "Swahili language",
        "Accessible book",
        "Protected DAISY",
        "Internet Archive Wishlist",
        "Ficc ʹa o (ge nero)",
        "Shi jie wen xue",
        "Xiao shuo",
        "Fantasi a",
        "Tong hua",
        "Suo xie",
        "Shao er du wu",
        "Pin yin du wu",
        "Children's stories, Chinese",
        "Chinese language",
        "Translations into Polish",
        "Ying yu",
        "Yu yan du wu",
        "Large type books",
        "Decision making",
        "Juvenile Wit and humor",
        "Conduct of life",
        "Illusion (Philosophy)",
        "Innocence (Psychology)",
        "Dreams",
        "Courts and courtiers",
        "Theft",
        "Courts",
        "Curiosité",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Prise de décision",
        "Humour pour la jeunesse",
        "Morale pratique",
        "Lieux imaginaires",
        "Illusion (Philosophie)",
        "Rêves",
        "Cartes à jouer",
        "Cours et courtisans",
        "Croquet (Jeu)",
        "Vol (Droit)",
        "Tribunaux",
        "Histoires pour enfants anglaises",
        "Literature, collections",
        "Fiction, short stories (single author)",
        "Contes de fées",
        "English fiction",
        "Translations into Ladino",
        "Nonsense literature",
        "Fantasmes",
        "Dinosaurier",
        "Utdöda djur",
        "Urtidsdjur",
        "Forntiden",
        "Geologi",
        "Evolution",
        "Jorden",
        "Fantastiske fortællinger",
        "Translations into Yiddish",
        "Criticism and interpretation",
        "History",
        "Alice's adventures in Wonderland (Carroll, Lewis)",
        "Alice in Wonderland;",
        "North",
      ],
      ia_collection: [
        "Boston_College_Library",
        "additional_collections",
        "americana",
        "audio_bookspoetry",
        "audiocitenet",
        "barryuniversity-ol",
        "binghamton-ol",
        "blc",
        "bostonpubliclibrary",
        "bostonuniversitylibraries-ol",
        "bpljordan-ol",
        "brynmawr-ol",
        "burstein",
        "cdl",
        "cnusd-ol",
        "dartmouthlibrary-ol",
        "denverpubliclibrary-ol",
        "europeanlibraries",
        "fedlink",
        "folksoundomy",
        "framingham-ol",
        "gettysburgcollege",
        "gutenberg",
        "gutenberg-audiobooks",
        "gwulibraries-ol",
        "iastaffselections",
        "inlibrary",
        "internet-books",
        "internetarchivebooks",
        "irishstudies",
        "juvenilehistoricalcollection",
        "kellylibrary",
        "library_of_congress",
        "librivoxaudio",
        "marygrovecollege",
        "marymount-ol",
        "microfilm",
        "newyorkpubliclibrary",
        "occidentalcollegelibrary-ol",
        "oliverwendellholmeslibrary",
        "openlibrary-d-ol",
        "phillipsacademy",
        "popularchinesebooks",
        "printdisabled",
        "rochester-ol",
        "spokanepubliclibrary-ol",
        "standardebooks",
        "stmaryscountylibrary",
        "thomasfisher",
        "toronto",
        "ualbertawiedrick",
        "unb-ol",
        "unclibraries",
        "uni-ol",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "worksintranslation",
        "worthingtonlibraries-ol",
        "wrlc-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL31727381M",
      lending_identifier: "alicesadventures00carr_759",
      authors: [
        {
          key: "/authors/OL22098A",
          name: "Lewis Carroll",
        },
      ],
      first_publish_year: 1865,
      ia: "alicesadventures00carr_759",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "error",
        error_message: "not found",
        identifier: "alicesadventures00carr_759",
        is_restricted: true,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL17732W",
      title: "Bible",
      edition_count: 3098,
      cover_id: 12707846,
      cover_edition_key: "OL39801870M",
      subject: [
        "Manuscripts, Latin (Medieval and modern)",
        "Glossaries, vocabularies",
        "Early works to 1800",
        "Bible",
        "Religion",
        "Bibles",
        "Biblical Studies - General",
        "Religion / Bible / General",
        "Bible - General",
        "Commentaries",
        "Authorized",
        "Criticism, interpretation",
        "Shorthand",
        "Sacred books",
        "Church of Jesus Christ of Latter-day Saints",
        "BÍBLIA (INTERPRETAÇÃO)",
        "Juvenile literature",
        "The Bible",
        "Biblia",
        "Christian life",
        "Study and teaching",
        "English Concordances",
        "Bible, study and teaching",
        "Jews",
        "Antiquities",
        "Apocryphal books (Old Testament)",
        "Education",
        "Doctrines",
        "Spiritual life",
        "Religious life",
        "New Testament",
        "Peshitta",
        "English Harmonies",
        "Bible, commentaries",
        "Introductions",
        "Biography",
        "Creation",
        "Biblical teaching",
        "History",
        "Bible, criticism, interpretation, etc.",
        "Catholic Truth Society (Great Britain)",
        "Church year meditations",
        "Lectionaries",
        "Bible, theology",
        "Bibel",
        "Bijbel",
        "Christianity",
        "Spirituality",
        "Bible. -- Old Testament",
        "Bible. -- New Testament",
        "Teenagers' use",
        "English Bible stories",
        "Bible stories",
        "Bible--Study and teaching--Catholic Church",
        "Catholic youth--Religious life",
        "Catholic youth",
        "Devotional calendars",
        "Christian women",
        "Prayers and devotions",
        "Women -- Prayer-books and devotions -- English",
        "Devotional exercises",
        "Couples",
        "Prayer-books and devotions",
        "Devotional use",
        "Older Christians",
        "Bible, meditations",
        "Older people, prayers and devotions",
        "Meditations",
        "Twelve-step programs",
        "Conduct of life",
        "Prayer books and devotions",
        "Teenagers",
        "Amplified",
        "Men's Bible",
        "Twelve-step programs -- Religious aspects -- Christianity -- Meditations",
        "Bible -- Meditations",
        "Women",
        "Mothers",
        "Sources",
        "Specimens",
        "Bibles - Living",
        "Religious aspects",
        "Teenage girls",
        "Devotional literature",
        "Men",
        "Church group work with men",
        "Study skills",
        "Children",
        "Children's use",
        "Blacks in the Bible",
        "Bibles, english standard version, study",
        "Faith",
        "Theology",
        "Chronology",
        "Bible - Reference Editions",
        "Bible, versions",
        "Bibles, other english translations, study",
        "Bibles, new international version, youth & teen",
        "Bibles, new king james version, youth & teen",
        "Bibles, king james version, study",
        "Bibles, christian standard bible, youth & teen",
        "Spiritual life, christianity",
        "Bibles, other english translations, youth & teen",
        "Bible, study",
        "Commentaires",
        "Methodist Church",
        "Holy Bible",
        "study bible",
        "Bibles, new revised standard version, study",
        "BIBLES / New Revised Standard Version / Study",
        "RELIGION / Biblical Criticism & Interpretation / General",
        "Evidences, authority",
        "Creationism",
        "Bible - Evidences, authority",
        "Bible - Study and teaching",
        "Authority",
        "Christian leadership",
        "Women in the Bible",
        "Juvenile",
        "Bible Study Guide",
        "God, knowableness",
        "Bible, criticism, interpretation, etc., n. t. epistles",
        "Jerusalem",
        "O.T.",
        "English Paraphrases",
        "Paraphrases",
        "Religion - Bibles - General",
        "Bible - Stories - Old Testament",
        "Paraphrases, English",
        "Students",
        "History of Biblical events",
        "Children, religious life",
        "In literature",
        "Bible, commentaries, o. t. apocrypha",
        "Characters",
        "Characters and characteristics",
        "Parenting",
        "Moral and ethical aspects",
        "Parents",
        "Geography",
        "Evidence",
        "Apologetics",
        "Missions",
        "Boys",
        "Bible -- Study and teaching",
        "Versiones",
        "Indexes",
        "Teenage boys",
        "Girls",
        "Personal narratives",
        "Pentecostalism",
        "Episcopalians",
        "Earthquakes",
        "Youth",
        "Reference",
        "Deuterocanonieke boeken",
        "Oude Testament",
        "Nieuwe Testament",
        "Bible. O.T. Apocrypha",
        "Apocrypha",
        "Critique, interprétation",
        "Comentarios",
        "Reader Development Collection",
        "Bibles, god's word, text",
        "Abridgements",
        "God",
        "Literal Translations",
        "Literal Translation",
        "Literal Bible",
        "New World",
        "Psalters",
        "collectionID:KellerChallenge",
        "Women Biblical scholars",
        "collectionID:EanesChallenge",
        "Étude et enseignement",
        "Almanachs spirituels",
        "Forecasting",
        "Forecasts",
        "Bible, reading",
        "Reference books",
        "Women, religious life",
        "Religion and theology",
        "Children, juvenile literature",
        "Livres en gros caractères",
        "Éditions de référence",
        "Bible, chronology",
        "Bible, use",
        "Quotations",
        "Citations",
        "Übersetzung",
        "Kommentar",
        "Ouvrages pour la jeunesse",
        "Usage par les enfants",
        "Holy books",
        "Bibles, new revised standard version, new testament & portions",
        "Environmental aspects",
        "Green movement",
        "Environmentalism",
        "Adolescents",
        "Vie religieuse",
        "Doctrinal Theology",
        "Families",
        "Holy Spirit",
        "Saint-Esprit",
        "Enseignement biblique",
        "Spiritual formation",
        "Église catholique",
        "Jeunesse catholique",
        "Paraphrases anglaises",
        "Christian men",
        "Recovery",
        "Old and new testament",
        "Vie chrétienne",
        "Bibles, la biblia de las americas, text",
        "collectionID:bannedbooks",
        "Translations into English",
        "Bible in literature",
        "Bibles, other english translations, text",
        "Bible, study and teaching, outlines, syllabi, etc.",
        "Bible, concordances",
        "Large type books",
        "Bible, versions, english",
        "Bibles, new international version, text",
        "Bible, juvenile literature",
        "Women, prayers and devotions",
        "Bibles, new international version, devotional",
        "Bibles, nueva version international, text",
        "Bibles, other english translations, reference",
        "Bibles, king james version, children",
        "Bibles, new revised standard version, text",
        "Bibles, new international reader's version, children",
        "Bibles, general",
        "Bibles, multiple translations, text",
        "Bibles, king james version, text",
        "Bibles, new international reader's version, study",
        "Bible, textbooks",
        "Devotional literature (selections: extracts, etc.)",
        "Bibles, new international reader's version, youth & teen",
        "Youth, religious life",
        "Bibles, new international version, children",
        "Devotional calendars, juvenile literature",
        "Bibles, new international version, general",
        "Bible, prophecies",
        "Prophecy, christianity",
        "African americans, religion",
        "God, worship and love",
        "Bibles, new international reader's version, general",
        "Introduction",
      ],
      ia_collection: [
        "Boston_College_Library",
        "Princeton",
        "PrincetonRR",
        "Wellesley_College_Library",
        "additional_collections",
        "ambslibrary-ol",
        "ambsplc",
        "americana",
        "americanuniversity-ol",
        "bannedbooks",
        "barryuniversity-ol",
        "belmont-ol",
        "binghamton-ol",
        "blc",
        "bostonpubliclibrary",
        "bostonuniversitylibraries",
        "bostonuniversitylibraries-ol",
        "bplhoughton",
        "bpljordan-ol",
        "brigham_young_university",
        "brighamyounguniversityhawaii",
        "brynmawr-ol",
        "calacademy-ol",
        "californiastateuniversityfresno-ol",
        "cardinalstritchuniversity__disabilityresources",
        "cdl",
        "claremont_school_of_theology",
        "cnusd-ol",
        "cornell",
        "cua-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "drakeuniversity-ol",
        "duke_libraries",
        "dulds",
        "europeanlibraries",
        "fedlink",
        "framingham-ol",
        "getty",
        "gettyphotographyincunabula",
        "goffstownlibrary-ol",
        "greatbooks",
        "gutenberg",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "iacl",
        "inlibrary",
        "internetarchivebookdrive",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "kalamazoocollege-ol",
        "library_of_atlantis",
        "library_of_congress",
        "marygrovecollege",
        "marymount-ol",
        "mavcor",
        "medicalheritagelibrary",
        "michigan_books",
        "microfilm",
        "miltonpubliclibrary-ol",
        "occidentalcollegelibrary-ol",
        "oliverwendellholmeslibrary",
        "openlibrary-d-ol",
        "palnilastcopies",
        "phillipsacademy",
        "pimslibrary",
        "printdisabled",
        "rachelmcbridelindsey",
        "randolph-macon-college-ol",
        "rcplondon",
        "riceuniversity-ol",
        "robarts",
        "rochester-ol",
        "saiacs-ol",
        "schooloftheologybostonu",
        "schroederlibrary-ol",
        "smithsonian",
        "spokanepubliclibrary-ol",
        "stmaryscountylibrary",
        "the-claremont-colleges-ol",
        "theology",
        "thomasfisher",
        "thomasfishercanadiana",
        "toronto",
        "trent_university",
        "trinitycollege",
        "tulsacc-ol",
        "ubclibrary",
        "udc-ol",
        "uhmauicollege-ol",
        "ukmhl",
        "unb-ol",
        "uni-ol",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "university_of_illinois_urbana-champaign",
        "university_pittsburgh",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "universityofthewest-ol",
        "wellcomelibrary",
        "wilsoncollege-ol",
        "worthingtonlibraries-ol",
        "yrlsc",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL39801859M",
      lending_identifier: "holybible0000vari_t4b6",
      authors: [
        {
          key: "/authors/OL2745568A",
          name: "Bible",
        },
      ],
      first_publish_year: 1200,
      ia: "holybible0000vari_t4b6",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "holybible0000vari_t4b6",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL17732W",
        openlibrary_edition: "OL39801859M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL29983W",
      title: "Little Women",
      edition_count: 1896,
      cover_id: 8775559,
      cover_edition_key: "OL27300715M",
      subject: [
        "Romans",
        "Jeunes filles",
        "Soeurs",
        "Sisters",
        "Young women",
        "Fiction",
        "Fiction, women",
        "Young women, fiction",
        "Family life",
        "Literatura Norte Americana",
        "Families",
        "Juvenile fiction",
        "March family (Fictitious characters)",
        "Domestic fiction",
        "Bildungsromans",
        "Historical fiction",
        "Children's fiction",
        "Family life, fiction",
        "Sisters, fiction",
        "New england, fiction",
        "March family (fictitious characters), fiction",
        "American fiction (fictional works by one author)",
        "Fiction, family life, general",
        "Mothers and daughters, fiction",
        "History",
        "Dictionaries",
        "English language",
        "Spanish",
        "Familias",
        "Hermanas",
        "Madre e hijas",
        "Mothers and daughters",
        "Ficción",
        "Young men",
        "Social life and customs",
        "Large type books",
        "Manners and customs",
        "Fiction, coming of age",
        "Family, fiction",
        "Fiction, family life",
        "Children: Grades 4-6",
        "Family",
        "Protected DAISY",
        "Accessible book",
        "Fiction, general",
        "Coloring books",
        "German",
        "Literarne študije",
        'Little women""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""',
        "Japanese language books",
        "New England",
        "Novela estadounidense",
        "Američki građanski rat",
        "ljubav",
        "obitelj",
        "odrastanje",
        "growing up",
        "žene",
        "New England in fiction",
        "Sisters in fiction",
        "Family life in fiction",
        "Mothers and daughters in fiction",
        "Young women in fiction",
        "Family in fiction",
        "Literature, collections",
        "American literature",
        "New England -- Fiction",
        "March family (Fictitious characters) -- Fiction",
        "Sisters -- Fiction",
        "Family life -- New England -- Fiction",
        "Mothers and daughters -- Fiction",
        "Young women -- Fiction",
        "Autobiographical fiction",
        "Children",
        "Children's",
        "Kids",
        "Juvenile",
        "American",
        "Classic",
        "Literature",
        "Historical",
        "Mothers",
        "Daughtes",
        "Married women",
        "Orphans",
        "Coming of life",
        "Manners",
        "Customs",
        "Conduct of life",
        "Social life",
        "open_syllabus_project",
        "Mother-daughter relationship",
        "Folklore",
        "Reading Level-Grade 5",
        "Reading Level-Grade 4",
        "Reading Level-Grade 7",
        "Reading Level-Grade 6",
        "Reading Level-Grade 8",
        "Fiction, biographical",
        "Buried treasure",
        "Pirates",
        "Adventure and adventurers",
        "Robin Hood (Legendary character)",
        "Legends",
        "English Adventure stories",
        "Jungle animals",
        "Feral children",
        "Jungles",
        "Animals",
        "Short stories",
        "Adaptations",
        "Fiction, historical, general",
        "Fiction, romance, general",
        "Chang pian xiao shuo",
        "Zhang pian xiao shuo",
        "AR 8.6.",
        "Animals, fiction",
        "Friendship, fiction",
        "England, fiction",
        "Treasure island (imaginary place), fiction",
        "British and irish fiction (fictional works by one author)",
        "Coming of age",
        "Spanish language materials",
        "Famille March (Personnages fictifs)",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Mères et filles",
        "Jeunes femmes",
        "Sœurs",
        "Familles",
        "Madres e hijas",
        "Novela juvenil",
        "Jóvenes (Mujeres)",
        "Materiales en español",
        "Novela",
        "FICTION / Classics",
        "Hermanos",
        "Familia",
        "Little women (Alcott, Louisa May)",
        "Literature: Classics",
        "Young Adult Books",
        "Romance",
        "Drama",
        "Roman pour la jeunesse",
        "Famille",
        "Frères et soeurs",
        "Romans, nouvelles",
        "Drama (dramatic works by one author)",
      ],
      ia_collection: [
        "additional_collections",
        "americana",
        "aozorabunko",
        "bpljordan-ol",
        "cdl",
        "cnusd-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gwulibraries-ol",
        "iacl",
        "inlibrary",
        "internetarchivebooks",
        "juvenilehistoricalcollection",
        "kalamazoocollege-ol",
        "library_of_atlantis",
        "marygrovecollege",
        "marymount-ol",
        "microfilm",
        "newyorkpubliclibrary",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "pratt",
        "printdisabled",
        "rbcgen",
        "spokanepubliclibrary-ol",
        "stmaryscountylibrary",
        "toronto",
        "trent_university",
        "tulsacc-ol",
        "unb-ol",
        "unclibraries",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "university_of_illinois_urbana-champaign",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "universityofthewest-ol",
        "uslprototype",
        "worthingtonlibraries-ol",
        "yrlsc",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7060579M",
      lending_identifier: "littlewomenormeg00alcoiala",
      authors: [
        {
          key: "/authors/OL26680A",
          name: "Louisa May Alcott",
        },
      ],
      first_publish_year: 1848,
      ia: "littlewomenormeg00alcoiala",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "littlewomenormeg00alcoiala",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL29983W",
        openlibrary_edition: "OL7060579M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL8193478W",
      title: "Oliver Twist",
      edition_count: 1400,
      cover_id: 13300802,
      cover_edition_key: "OL47307472M",
      subject: [
        "Bildungsromans",
        "Boys",
        "Brigands and robbers",
        "British and irish fiction (fictional works by one author)",
        "British fiction",
        "Children",
        "Children's fiction",
        "Children's stories",
        "Classic",
        "Coming of age",
        "Criminals",
        "Criminels",
        "Criticism and interpretation",
        "Customs",
        "Enfants pauvres",
        "English language",
        "English literature",
        "Fiction",
        "fiction classics",
        "Historical fiction",
        "History",
        "Identity (Psychology)",
        "Juvenile fiction",
        "Kidnapping",
        "Kidnapping victims",
        "Literature",
        "Literature and fiction",
        "Manners and customs",
        "Manuels pour allophones",
        "Missing persons",
        "Novels",
        "Orphans",
        "Poor children",
        "Poverty",
        "Readers",
        "Robbers and outlaws",
        "Social conditions",
        "Social life",
        "Social life and customs",
        "Sources",
        "Stories",
        "Street life",
        "Thieves",
        "Victimes d'enlèvement",
        "Victims",
        "Vie dans la rue",
        "YA",
        "Young adult",
        "serials",
        "workhouses",
        "child labour",
        "domestic violence",
        "street children",
        "Kidnap victims",
        "Pickpockets",
        "English fiction",
        "Orphans -- Juvenile drama",
        "Children's plays, English",
        "London (England) -- Social conditions -- 19th century -- Juvenile drama",
        "Poor",
      ],
      ia_collection: [
        "Princeton",
        "americana",
        "audio_bookspoetry",
        "bethmardutho",
        "binghamton-ol",
        "blc",
        "bostonuniversitylibraries-ol",
        "cdl",
        "claremont_school_of_theology",
        "cnusd-ol",
        "cornell",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "europeanlibraries",
        "framingham-ol",
        "gutenberg",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "johnshopkins-ol",
        "kalamazoocollege-ol",
        "kellylibrary",
        "library_of_atlantis",
        "library_of_congress",
        "librivoxaudio",
        "marygrovecollege",
        "marymount-ol",
        "miltonpubliclibrary-ol",
        "nationalyiddishbookcenter",
        "oliverwendellholmeslibrary",
        "openlibrary-d-ol",
        "phillipsacademy",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "riceuniversity-ol",
        "robarts",
        "rochester-ol",
        "stmaryscountylibrary",
        "toronto",
        "trent_university",
        "tulsacc-ol",
        "ualbertawiedrick",
        "uconn_libraries",
        "uhmauicollege-ol",
        "university_of_alberta_libraries",
        "university_of_illinois_urbana-champaign",
        "universityofarizona-ol",
        "universityofoklahoma-ol",
        "universityofthewest-ol",
        "universitywesterno",
        "worthingtonlibraries-ol",
        "wrlc-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL46835116M",
      lending_identifier: "olivertwist0000char_v6j2",
      authors: [
        {
          key: "/authors/OL24638A",
          name: "Charles Dickens",
        },
      ],
      first_publish_year: 1838,
      ia: "olivertwist0000char_v6j2",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "olivertwist0000char_v6j2",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL8193478W",
        openlibrary_edition: "OL46835116M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL151406W",
      title: "Through the Looking-Glass",
      edition_count: 1185,
      cover_id: 11272464,
      cover_edition_key: "OL21298716M",
      subject: [
        "Fantasy",
        "Fiction",
        "English Nonsense verses",
        "Children's poetry, English",
        "Nonsense verses",
        "English poetry",
        "Alice (Fictitious character : Carroll)",
        "Toy and movable books",
        "English Fantasy poetry",
        "Children's stories",
        "Juvenile literature",
        "Specimens",
        "Juvenile fiction",
        "Translations into Italian",
        "Artists' books",
        "Shaw alphabet",
        "Children's stories, English",
        "Children's fiction",
        "Fantasy fiction",
        "Alice (fictitious character : carroll), fiction",
        "British and irish fiction (fictional works by one author)",
        "Fiction, fantasy, general",
        "Children's poetry",
        "Adventure and adventurers, fiction",
        "Large type books",
        "Classic Literature",
        "Translations into German",
        "Children's literature",
        "Dictionaries",
        "English language",
        "Spanish",
        "Imaginary places",
        "Korean",
        "German",
        "Chinese",
        "Child and youth fiction",
        "Fiction in English",
        "Texts",
        "Latin language",
        "Translations into French",
        "English Fantasy fiction",
        "Girls, fiction",
        "Literature and fiction, juvenile",
        "Fairy tales",
        "Literature and fiction (general)",
        "Literature and fiction, fantasy",
        "Sick, fiction",
        "English language, study and teaching, foreign speakers",
        "English literature",
        "Novela inglesa",
        "Literatura inglesa",
        "Fantasmes",
        "Romans, nouvelles, etc. pour la jeunesse",
        "DREAMS",
        "Physics, mathematical models",
        "Imagination",
        "Curiosity",
        "Decision making",
        "Juvenile Wit and humor",
        "Children",
        "Conduct of life",
        "Adventure and adventurers",
        "Illusion (Philosophy)",
        "Queens",
        "Chess",
        "Twins",
        "Unicorns",
        "Animals",
        "Insects",
        "Flowers",
        "Portmanteau words",
        "Fiction, classics",
      ],
      ia_collection: [
        "americana",
        "audio_bookspoetry",
        "barryuniversity-ol",
        "binghamton-ol",
        "bpljordan-ol",
        "brynmawr-ol",
        "burstein",
        "cnusd-ol",
        "duke_libraries",
        "framingham-ol",
        "gettysburgcollege",
        "gutenberg",
        "gutenberg-audiobooks",
        "iacl",
        "inlibrary",
        "internetarchivebooks",
        "juvenilehistoricalcollection",
        "library_of_congress",
        "librivoxaudio",
        "marygrovecollege",
        "newyorkpubliclibrary",
        "openlibrary-d-ol",
        "printdisabled",
        "riceuniversity-ol",
        "robarts",
        "toronto",
        "ualberta_historical_school",
        "unb-ol",
        "unclibraries",
        "university_of_alberta_libraries",
        "universityofoklahoma-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL21298716M",
      lending_identifier: "throughlookinggl01carr",
      authors: [
        {
          key: "/authors/OL22098A",
          name: "Lewis Carroll",
        },
      ],
      first_publish_year: 1871,
      ia: "throughlookinggl01carr",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "throughlookinggl01carr",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL151406W",
        openlibrary_edition: "OL21298716M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL18417W",
      title: "The Wonderful Wizard of Oz",
      edition_count: 1029,
      cover_id: 552443,
      cover_edition_key: "OL8155451M",
      subject: [
        "Witches",
        "Toy and movable books",
        "Spanish language materials",
        "Fiction",
        "Wizards",
        "Juvenile literature",
        "Wizards in fiction",
        "Children's stories, Russian",
        "Specimens",
        "Imaginary voyages in fiction",
        "Classic Literature",
        "Imaginary Voyages",
        "Children's stories, American",
        "Adventure and adventurers",
        "Open Library Staff Picks",
        "Books and reading",
        "Children's stories",
        "Witches in fiction",
        "History",
        "Juvenile fiction",
        "Latin language materials",
        "Fairy tales",
        "Children",
        "Contes americains",
        "Ouvrages pour la jeunesse",
        "Fantasy",
        "Fantasy fiction",
        "Fantastic fiction",
        "Novela fantástica",
        "Fantasía",
        "Teenage girls",
        "Quests (Expeditions)",
        "Oz (Imaginary place)",
        "Children's fiction",
        "Oz (imaginary place), fiction",
        "Fiction, fantasy, general",
        "Young adult fiction",
        "Fiction, science fiction, general",
        "Wizards, fiction",
        "Fantasy & Magic",
        "Classics",
        "Literature and fiction, juvenile",
        "American Fantasy fiction",
        "History and criticism",
        "Large type books",
        "Dorothy Gale (Fictional character)",
        "French language materials",
        "American literature",
        "Children: Babies Toddlers",
        "Wizard of Oz (Fictitious character)",
        "Friendship",
        "Courage",
        "Adventure stories",
        "Dorothy Gale (Fictitious character)",
        "Children's literature",
        "General",
        "Contes américains",
        "Roman pour la jeunesse",
        "Contes",
        "Tong hua",
        "Er tong wen xue",
        "Han yu pin yin",
        "Er tong du wu",
        "Translations into Chinese",
        "Suo xie ben",
        "Chinese language materials",
        "Ying yu",
        "Dui zhao du wu",
        "Han yu",
        "Pictorial works",
        "Robots, fiction",
        "Science fiction",
        "Criticism and interpretation",
        "Wizard of Oz (Baum, L. Frank)",
        "Fiction, general",
        "Film adaptations",
        "Oz (Imaginary place) -- Juvenile fiction",
        "Fantasy literature",
        "Courage -- Juvenile fiction",
        "Home -- Juvenile fiction",
        "Good and evil -- Juvenile fiction",
        "Dreams -- Juvenile fiction",
        "Gale, Dorothy (Fictitious character) -- Juvenile fiction",
        "Cowardly Lion (Fictitious character) -- Juvenile fiction",
        "Cyclones -- Juvenile fiction",
        "Scarecrow (Fictitious character from Baum) -- Juvenile fiction",
        "Toto (Fictitious character) -- Juvenile fiction",
        "Witches -- Juvenile fiction",
        "Wizard of Oz (Fictitious character) -- Juvenile fiction",
        "Tin Woodman (Fictitious character) -- Juvenile fiction",
        "Adventure and adventurers, fiction",
        "Witches, fiction",
        "Scarecrow (Fictitious character : Baum)",
        "Tin Woodman (Fictitious character)",
        "Cowardly Lion (Fictitious character)",
        "Oz (Lieu imaginaire)",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Friendship, fiction",
        "People with disabilities, fiction",
        "Great britain, fiction",
        "American fiction (fictional works by one author)",
        "Picture books",
        "Fables",
        "Toto (Fictitious character)",
        "Good and evil",
        "Motion picture plays",
        "Juvenile drama",
        "JUVENILE FICTION / Fantasy & Magic",
      ],
      ia_collection: [
        "americana",
        "americanuniversity-ol",
        "bannedbooks",
        "bpljordan-ol",
        "cdl",
        "cnusd-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "iacl",
        "inlibrary",
        "internetarchivebooks",
        "johnshopkins-ol",
        "library_of_atlantis",
        "marygrovecollege",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "rochester-ol",
        "stmaryscountylibrary",
        "the-claremont-colleges-ol",
        "unb-ol",
        "uni-ol",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "wilsoncollege-ol",
        "worthingtonlibraries-ol",
        "wrlc-ol",
        "yrlsc",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7170815M",
      lending_identifier: "wonderfulwizardo00baumiala",
      authors: [
        {
          key: "/authors/OL9348793A",
          name: "L. Frank Baum",
        },
      ],
      first_publish_year: 1900,
      ia: "wonderfulwizardo00baumiala",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "wonderfulwizardo00baumiala",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL18417W",
        openlibrary_edition: "OL7170815M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL53919W",
      title: "The Adventures of Tom Sawyer",
      edition_count: 877,
      cover_id: 12043351,
      cover_edition_key: "OL34596309M",
      subject: [
        "The Adventures of Tom Sawyer",
        "Mark Twain",
        "1835-1910",
        "19th Century",
        "Historical",
        "Fiction",
        "Classic",
        "American",
        "Novel",
        "Children",
        "Children's",
        "Kid's",
        "Juvenile",
        "Young Adult",
        "ADULT",
        "1967 Lewis Carroll Shelf Award",
        "Literature",
        "Hardcover",
        "Paperback",
        "Kindle",
        "E-book",
        "Free online",
        "Dummies (Bookselling)",
        "Manuscripts",
        "American Manuscripts",
        "Movies",
        "Theatre",
        "Theater",
        "Adventure stories",
        "Novels, other prose & writers: 19th century",
        "Male friendship",
        "Adventure",
        "Adventures",
        "Adventurerers",
        "Stories",
        "Books",
        "Readers",
        "Runaway children",
        "Child witnesses",
        "Fugitive slaves",
        "Race relations",
        "Boys",
        "Readers for new literates",
        "High interest-low vocabulary books",
        "open_syllabus_project",
        "Sawyer, Tom (Personaje literario)",
        "Relatos de aventura",
        "Muchachos",
        "Cartoons and comics",
        "History",
        "Social life and customs",
        "Niños",
        "Translations",
        "Russian",
        "Spanish",
        "Polish",
        "Czech",
        "Ficción juvenil",
        "Juvenile fiction",
        "Klassenlektüre",
        "Englischunterricht",
        "Translations into Czech",
        "Children's stories, American",
        "Tom Sawyer (Fictitious character)",
        "Children's fiction",
        "Mississippi river, fiction",
        "Missouri, fiction",
        "Adventure and adventurers, fiction",
        "Sawyer, tom (fictitious character), fiction",
        "American fiction (fictional works by one author)",
        "Fiction, action & adventure",
        "Fiction, humorous",
        "Mississippi, fiction",
        "Slaves, fiction",
        "Southern states, fiction",
        "Comics & graphic novels, literary",
        "Fiction, general",
        "Suo xie ben",
        "Er tong wen xue",
        "Chang pian xiao shuo",
        "Huckleberry Finn (Fictitious character)",
        "Adventure fiction",
        "Adventure and adventurers",
        "Graphic novels",
        "Comic books, strips",
        "Facsimiles",
        "Specimens",
        "Large type books",
        "American Adventure stories",
        "History and criticism",
        "Manners and customs",
        "Runaways",
        "Adaptations",
        "Witnesses",
        "Runaways, fiction",
        "American literature",
        "FICTION / Classics",
        "FICTION / Literary",
        "Aventures et aventuriers",
        "Romans",
        "Orphelins",
        "Children's stories",
        "Conduct of life",
        "Abenteuer",
        "Waisenkind",
        "Ouvrages de fiction",
        "FICTION / Action & Adventure",
        "Boys, fiction",
        "Fiction, humorous, general",
        "Humorous stories",
        "Behavior, fiction",
        "Literature and fiction, juvenile",
        "Friendship, fiction",
        "Literature, collections",
        "AR 8.3.",
        "Spanish language materials",
        "Sawyer, Tom (Personaje imaginario)",
        "Novela",
        "Novela de acción y aventura",
        "Novela humorística",
        "Novela estadounidense",
        "Garçons",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Tom Sawyer (Fictional character)",
        "English language, textbooks for foreign speakers",
        "Finn, huckleberry (fictitious character), fiction",
      ],
      ia_collection: [
        "_locker-hank_b",
        "additional_collections",
        "americana",
        "americanuniversity-ol",
        "audio_bookspoetry",
        "bannedbooks",
        "bell",
        "bell_literature",
        "belmont-ol",
        "blc",
        "booksbylanguage",
        "booksbylanguage_urdu",
        "bostonpubliclibrary",
        "bostonuniversitylibraries-ol",
        "bpljordan-ol",
        "cdl",
        "cnusd-ol",
        "cornell",
        "cua-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gutenberg",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "iacl",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "library_of_atlantis",
        "library_of_congress",
        "librivoxaudio",
        "marygrovecollege",
        "marymount-ol",
        "microfilm",
        "nationalyiddishbookcenter",
        "newyorkpubliclibrary",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "robarts",
        "rochester-ol",
        "spokanepubliclibrary-ol",
        "stmaryscountylibrary",
        "the-claremont-colleges-ol",
        "thomasfisher",
        "thomasfishercanadiana",
        "toronto",
        "trent_university",
        "tulsacc-ol",
        "ualbertawiedrick",
        "uconn_libraries",
        "unb-ol",
        "uni-ol",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "universityofthewest-ol",
        "wilsoncollege-ol",
        "worthingtonlibraries-ol",
        "yrlsc",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL25098005M",
      lending_identifier: "cihm_93635",
      authors: [
        {
          key: "/authors/OL18319A",
          name: "Mark Twain",
        },
      ],
      first_publish_year: 1817,
      ia: "cihm_93635",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "cihm_93635",
        isbn: "0665936354",
        oclc: null,
        openlibrary_work: "OL53919W",
        openlibrary_edition: "OL25098005M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL69612W",
      title: "The Secret Garden",
      edition_count: 762,
      cover_id: 12622062,
      cover_edition_key: "OL37044748M",
      subject: [
        "Fiction, general",
        "Friendship, fiction",
        "People with disabilities, fiction",
        "Great britain, fiction",
        "Child and youth fiction",
        "Children's fiction",
        "Gardens, fiction",
        "England, fiction",
        "American literature",
        "Orphans, fiction",
        "Great britain, history, fiction",
        "English language",
        "Orphans",
        "Juvenile fiction",
        "Gardens",
        "Fiction",
        "Children with disabilities",
        "Loneliness in children",
        "Fiction, coming of age",
        "Fantasy fiction",
        "Toy and movable books",
        "American fiction",
        "People with disabilities",
        "Stories",
        "Huérfanos",
        "Ficción juvenil",
        "Jardines",
        "Impedidos",
        "Friendship",
        "Sick children",
        "History",
        "Families",
        "Pictorial works",
        "Familles",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Amitié",
        "Jardins",
        "Ouvrages illustrés",
        "Children's stories, American",
        "Great Britain",
        "Personnes handicapées",
        "Girls, fiction",
        "American literature, study and teaching",
        "American fiction, history and criticism",
        "Children",
        "Enfants",
        "Romans, nouvelles",
        "Orphelins",
        "Roman pour la jeunesse",
        "Physically handicapped",
        "England",
        "Literature",
        "Dictionaries",
        "Chinese",
        "Selbsterziehung",
        "Freundschaft",
        "Garten",
        "Waisenkind",
        "Korean",
        "Spanish",
        "French",
        "Therapeutic use",
        "Gardening",
        "Cousins",
        "Spanish language materials",
        "Detective and mystery stories",
        "reading",
        "strategies",
        "classic",
        "Accessible book",
        "Protected DAISY",
        "Physically disabled children",
        "Children's stories, English",
        "People with physical disabilities",
        "Juvenile literature",
        "Children's stories",
        "JUVENILE FICTION / Family / Orphans & Foster Homes",
        "JUVENILE FICTION / Girls & Women",
        "JUVENILE FICTION / Social Themes / Friendship",
        "JUVENILE FICTION / Lifestyles / Country Life",
        "JUVENILE FICTION / Disabilities & Special Needs",
        "English language, textbooks for foreign speakers",
        "Readers",
        "British and irish fiction (fictional works by one author)",
        "Grandparents, fiction",
        "Great britain, history, 19th century, fiction",
        "Grandfathers",
        "Language and languages, study and teaching",
      ],
      ia_collection: [
        "americana",
        "belmont-ol",
        "binghamton-ol",
        "bpljordan-ol",
        "cnusd-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "johnshopkins-ol",
        "library_of_atlantis",
        "miltonpubliclibrary-ol",
        "newyorkpubliclibrary",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "printdisabled",
        "randolph-macon-college-ol",
        "riceuniversity-ol",
        "rochester-ol",
        "stmaryscountylibrary",
        "uhmauicollege-ol",
        "unb-ol",
        "uni-ol",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7096476M",
      lending_identifier: "secretgarden00burn",
      authors: [
        {
          key: "/authors/OL23767A",
          name: "Frances Hodgson Burnett",
        },
      ],
      first_publish_year: 1911,
      ia: "secretgarden00burn",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "secretgarden00burn",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL69612W",
        openlibrary_edition: "OL7096476M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL262460W",
      title: "The Lost World",
      edition_count: 745,
      cover_id: 8231444,
      cover_edition_key: "OL22885694M",
      subject: [
        "Adventure stories",
        "Atlantis",
        "Dinosaurs",
        "Discovery and exploration",
        "English Detective and mystery stories",
        "Fiction",
        "Fiction in English",
        "Fiction in French",
        "Prehistoric peoples",
        "Professor Challenger (Fictitious character)",
        "Scientific expeditions",
        "Translations into Czech",
        "Translations into Russian",
        "Science fiction",
        "Fantasy",
        "Discoveries in geography",
        "Children's fiction",
        "Dinosaurs, fiction",
        "Fiction, fantasy, general",
        "Fiction, action & adventure",
        "Challenger, professor (fictitious character), fiction",
        "South america, fiction",
        "Books and reading",
        "Public libraries",
        "Activity programs",
        "Criticism and interpretation",
        "Reading promotion",
        "Young adults' libraries",
        "Westminster Libraries and Archives",
        "Youth",
        "Lost world (Doyle, Arthur Conan)",
        "Children",
        "British and irish fiction (fictional works by one author)",
        "Fiction, science fiction, general",
        "Scientists, fiction",
        "English literature",
        "Large type books",
        "Fiction, historical, general",
        "Romans, nouvelles",
        "Dinosaures",
        "Challenger, Professor (Personaje literario)",
        "Novela",
        "Pueblos prehistóricos",
        "Dinosaurios",
        "Adventure and adventurers, fiction",
        "Fiction, general",
        "Challenger, Professor (Fictitious character) -- Fiction",
        "Fantasy fiction",
        "South America -- Fiction",
        "Prehistoric peoples -- Fiction",
        "Dinosaurs -- Fiction",
        "Literature and fiction, action and adventure",
        "New York Times reviewed",
        "Prehistoric peoples, fiction",
        "Scientific expeditions, fiction",
        "South America",
      ],
      ia_collection: [
        "additional_collections",
        "americana",
        "audio_bookspoetry",
        "binghamton-ol",
        "cdl",
        "cnusd-ol",
        "cornell",
        "delawarecountydistrictlibrary",
        "friendsofthesanfranciscopubliclibrary",
        "gutenberg",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "library_of_atlantis",
        "librivoxaudio",
        "microfilm",
        "openlibrary-d-ol",
        "printdisabled",
        "riceuniversity-ol",
        "robarts",
        "rochester-ol",
        "sciencefiction",
        "toronto",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL43177171M",
      lending_identifier: "lostworld0000sira_n3v3",
      authors: [
        {
          key: "/authors/OL161167A",
          name: "Arthur Conan Doyle",
        },
      ],
      first_publish_year: 1900,
      ia: "lostworld0000sira_n3v3",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "lostworld0000sira_n3v3",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL31513113W",
        openlibrary_edition: "OL43177171M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL10322056W",
      title: "David Copperfield",
      edition_count: 702,
      cover_id: 13115624,
      cover_edition_key: "OL44903680M",
      subject: [
        "Fiction",
        "Orphans",
        "Young men",
        "Boys",
        "Stepfathers",
        "Child labor",
        "Novelists",
        "Social life and customs",
        "History",
        "Mongolian literature",
        "Coming of age",
        "Accessible book",
        "OverDrive",
        "Classic Literature",
        "Literature",
        "Drama",
        "Historical Fiction",
        "Protected DAISY",
        "Juvenile fiction",
        "Employment",
        "Children",
        "In library",
        "Large type books",
        "Girls",
        "Bildungsromane",
        "Autobiographical fiction",
        "British fiction",
        "British and irish fiction (fictional works by one author)",
        "England, fiction",
        "Fiction, coming of age",
        "Children's fiction",
        "Orphans, fiction",
        "Boys, fiction",
        "Stepparents, fiction",
        "English literature",
        "Adaptations",
        "High interest-low vocabulary books",
        "Manners and customs",
        "Readers for new literates",
        "David Copperfield (Motion picture : 1935)",
        "Poor children",
        "Social classes",
        "Social conditions",
        "Fiction, family life, general",
        "British and irish drama (dramatic works by one author)",
        "Romans, nouvelles",
        "Mœurs et coutumes",
        "Jeunes hommes",
        "Spanish language materials",
        "Problems, exercises",
        "Textbooks for foreign speakers",
        "Reading comprehension",
        "English language",
        "Readers (Adult)",
        "Romanciers",
        "Beaux-pères",
        "Enfants",
        "Travail",
        "Fiction, general",
        "England -- Social life and customs -- 19th century -- Fiction",
        "Boys -- Fiction",
        "Orphans -- Fiction",
        "Young men -- Fiction",
        "Stepfathers -- Fiction",
        "Child labor -- Fiction",
        "England -- Fiction",
        "Bildungsromans",
        "Chang pian xiao shuo",
        "English language, textbooks for foreign speakers",
        "General",
        "Rabbits, fiction",
        "Mice, fiction",
      ],
      ia_collection: [
        "additional_collections",
        "americana",
        "audio_bookspoetry",
        "bpljordan-ol",
        "brigham_young_university",
        "cdl",
        "cnusd-ol",
        "cua-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "duke_libraries",
        "europeanlibraries",
        "framingham-ol",
        "greatbooks",
        "gutenberg",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "harvardclassicssingles",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "kalamazoocollege-ol",
        "kellylibrary",
        "library_of_atlantis",
        "library_of_congress",
        "librivoxaudio",
        "marygrovecollege",
        "marymount-ol",
        "michigan_books",
        "microfilm",
        "nationalyiddishbookcenter",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "robarts",
        "rochester-ol",
        "sablecentre",
        "stmaryscountylibrary",
        "toronto",
        "tulsacc-ol",
        "uni-ol",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofottawa",
        "victorianbrighamyounguniv",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL44094098M",
      lending_identifier: "dickenswork04dick",
      authors: [
        {
          key: "/authors/OL24638A",
          name: "Charles Dickens",
        },
      ],
      first_publish_year: 1800,
      ia: "dickenswork04dick",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "dickenswork04dick",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL10322056W",
        openlibrary_edition: "OL44094098M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL99499W",
      title: "Five Children and It",
      edition_count: 611,
      cover_id: 28174,
      cover_edition_key: "OL9232844M",
      subject: [
        "Fiction",
        "Fairies",
        "Wishes",
        "Brothers and sisters",
        "History",
        "Juvenile fiction",
        "Fantasy",
        "Fairy tales",
        "Stories",
        "England",
        "Fantasy fiction",
        "Children's stories, English",
        "Amulets",
        "Fiction in English",
        "Children's fiction",
        "Fairies, fiction",
        "Brothers and sisters, fiction",
        "England, fiction",
        "Children, fiction",
        "Readers",
        "Large type books",
        "Readers (Adult)",
        "English language",
        "Textbooks for foreign speakers",
        "Reading comprehension",
        "Problems, exercises",
        "Children",
        "Brothers and sisters -- Fiction",
        "Wishes -- Fiction",
        "Fairies -- Fiction",
        "Great Britain -- History -- Edward VII, 1901-1910 -- Fiction",
        "Fiction, general",
        "Fées",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Souhaits",
        "Frères et sœurs",
        "Histoire",
        "Fiction, action & adventure",
        "Family",
        "Siblings, fiction",
      ],
      ia_collection: [
        "americana",
        "belmont-ol",
        "bpljordan-ol",
        "china",
        "cnusd-ol",
        "delawarecountydistrictlibrary",
        "framingham-ol",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "library_of_atlantis",
        "librarygenesis",
        "marymount-ol",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7353846M",
      lending_identifier: "fivechildrenitpu00enes",
      authors: [
        {
          key: "/authors/OL18053A",
          name: "Edith Nesbit",
        },
      ],
      first_publish_year: 1905,
      ia: "fivechildrenitpu00enes",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: true,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "fivechildrenitpu00enes",
        isbn: "0140350616",
        oclc: null,
        openlibrary_work: "OL99499W",
        openlibrary_edition: "OL7353846M",
        last_loan_date: "2020-09-04T19:04:38Z",
        num_waitlist: "0",
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL151411W",
      title: "Alice's Adventures in Wonderland / Through the Looking Glass",
      edition_count: 546,
      cover_id: 8595966,
      cover_edition_key: "OL25129289M",
      subject: [
        "adventure and adventurers",
        "adventure and adventurers, fiction",
        "adventure stories",
        "adventure travel",
        "animals",
        "anthropomorphism",
        "artists' illustrated books",
        "books and reading",
        "british and irish fiction (fictional works by one author)",
        "child and youth fiction",
        "children",
        "children's fiction",
        "children's literature",
        "children's literature, english",
        "children's stories",
        "children's stories, english",
        "classic literature",
        "classics",
        "croquet",
        "curiosity",
        "curiosity in children",
        "english",
        "english adventure stories",
        "english fantastic fiction",
        "english fantasy fiction",
        "english fantasy literature",
        "english language",
        "english literature",
        "english nonsense verses",
        "fairy tales",
        "fantasy",
        "fantasy & magic",
        "fantasy fiction",
        "fantasy in fiction",
        "fantasy  magic",
        "fiction",
        "friendship",
        "girls",
        "girls, fiction",
        "hookahs",
        "humor",
        "humorous stories",
        "illustrations",
        "imaginary places",
        "imagination & play",
        "juvenile fiction",
        "juvenile literature",
        "legends",
        "literary nonsense",
        "logic",
        "mythical animals",
        "nonsense verses",
        "playing cards",
        "rabbits",
        "readers",
        "reading materials",
        "short novel",
        "tea",
        "texts",
        "Specimens",
        "Textual Criticism",
        "Criticism and interpretation",
        "Open Library Staff Picks",
        "Ficción juvenil",
        "Novela fantástica",
        "Portuguese language materials",
        "Fantasía",
        "History",
        "History and criticism",
        "CHR 1960",
        "PRO Tehon, Susan (donor)",
        "Alice (Fictitious character : Carroll)",
        "PRO Tehon, Atha (former owner) (Tehon Collection copy)",
        "Littérature anglaise",
        "18.05 English literature",
        "Alice (fictitious character : carroll), fiction",
        "Fiction, fantasy, general",
        "Fiction in English",
        "Carroll, lewis, 1832-1898",
        "Large type books",
        "Translations into French",
        "JUVENILE FICTION / Action & Adventure / General",
        "JUVENILE FICTION / Classics",
        "JUVENILE FICTION / Fairy Tales & Folklore / Adaptations",
        "English fiction (collections), 20th century",
        "Rabbits, fiction",
        "English fiction",
        "Picture books",
        "Alice (Fictitious character)",
        "Accessible book",
        "Condensed books",
        "Through the looking glass",
        "Alice's adventures in Wonderland (Carroll, Lewis)",
        "Through the looking-glass (Carroll, Lewis)",
        "Literature",
        "Translations into Polish",
        "Imaginary Voyages",
        "Literatură engleză",
        "Roman",
        "Literatură pentru copii",
        "Novela fantástica inglesa",
        "Traducciones al español",
        "Literatura inglesa",
        "Flickor",
        "Barn- och ungdomslitteratur",
        "Drömmar",
        "Fantasiresor",
        "Parallella världar",
        "Fiction, general",
        "Philosophy",
        "Literature, collections",
        "Tong hua",
        "Zuo pin ji",
        "Children's stories, English",
      ],
      ia_collection: [
        "americana",
        "americanuniversity-ol",
        "bannedbooks",
        "binghamton-ol",
        "bpljordan-ol",
        "cdl",
        "cnusd-ol",
        "cua-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "duke_libraries",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gwulibraries-ol",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "juvenilehistoricalcollection",
        "library_of_atlantis",
        "library_of_congress",
        "marygrovecollege",
        "newyorkpubliclibrary",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "rochester-ol",
        "stmaryscountylibrary",
        "the-claremont-colleges-ol",
        "trent_university",
        "tulsacc-ol",
        "udc-ol",
        "unb-ol",
        "unclibraries",
        "uni-ol",
        "university_of_illinois_urbana-champaign",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "wilsoncollege-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL26314337M",
      lending_identifier: "alicesadventures00carr_13",
      authors: [
        {
          key: "/authors/OL22098A",
          name: "Lewis Carroll",
        },
      ],
      first_publish_year: 1889,
      ia: "alicesadventures00carr_13",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "alicesadventures00carr_13",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL151411W",
        openlibrary_edition: "OL26314337M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
  ],
};
